apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: grpc-collector
      protocol: TCP
      port: 4317
      targetPort: 55680
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
  selector:
    app: jaeger
