apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-plugin-zipkin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  local_service_name: kong
  http_endpoint: http://zipkin.default.svc.cluster.local:9411/api/v2/spans
  sample_ratio: 1.0
  include_credential: true
  traceid_byte_count: 16
  header_type: preserve
  default_header_type: b3
  tags_header: Zipkin-Tags
plugin: zipkin